version: '3'
services:
  api:
    build: .
    ports:
      - 3001:3001
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ozmap
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27018:27018"
    networks:
      - mongo-compose-network
networks: 
    mongo-compose-network:
      driver: bridge